hue4cpp: hue4cpp::Bridge::Impl Class Reference
hue4cpp::Bridge::Impl Class Reference
Public Member Functions
Impl (Bridge *bridge)
Impl (const BridgeInfo &bridge_info, Bridge *bridge)
Impl (Impl &&other) noexcept
template<typename SensorType >
std::vector< std::unique_ptr< SensorType > > fetchSensorsByType (const std::string &resource_type, Bridge *bridge)
Public Attributes
BridgeInfo info
std::string auth_key
std::unique_ptr< StateManager > state_manager
Detailed Description
Definition at line 21 of file bridge.cpp.
Constructor & Destructor Documentation
Impl() [1/3]
hue4cpp::Bridge::Impl::Impl (Bridge * bridge) inline
Definition at line 27 of file bridge.cpp.
Impl() [2/3]
hue4cpp::Bridge::Impl::Impl (const BridgeInfo & bridge_info, Bridge * bridge) inline explicit
Definition at line 28 of file bridge.cpp.
Impl() [3/3]
hue4cpp::Bridge::Impl::Impl (Impl && other) inline noexcept
Definition at line 32 of file bridge.cpp.
Member Function Documentation
fetchSensorsByType()
template<typename SensorType > std::vector< std::unique_ptr< SensorType > > hue4cpp::Bridge::Impl::fetchSensorsByType (const std::string & resource_type, Bridge * bridge) inline
Definition at line 40 of file bridge.cpp.
References auth_key, hue4cpp::HttpClient::get(), hue4cpp::json_utils::getValue(), info, hue4cpp::BridgeInfo::ip_address, hue4cpp::json_utils::parse(), hue4cpp::HttpClient::setTimeout(), and hue4cpp::HttpClient::setVerifySsl().
Member Data Documentation
auth_key
std::string hue4cpp::Bridge::Impl::auth_key
Definition at line 24 of file bridge.cpp.
Referenced by fetchSensorsByType().
info
BridgeInfo hue4cpp::Bridge::Impl::info
Definition at line 23 of file bridge.cpp.
Referenced by fetchSensorsByType().
state_manager
std::unique_ptr<StateManager> hue4cpp::Bridge::Impl::state_manager
Definition at line 25 of file bridge.cpp.
The documentation for this class was generated from the following file:
src/bridge.cpp