hue4cpp: hue4cpp::SSEClient::Impl Class Reference
hue4cpp::SSEClient::Impl Class Reference
Public Member Functions
Impl (const std::string &endpoint_url)
~Impl ()
void stopConnection ()
void notifyConnectionChange (bool is_connected)
void notifyEvent (const SSEEvent &event)
bool parseSSELine (const std::string &line, SSEEvent &current_event)
Parse SSE stream data.
void connectionLoop ()
Public Attributes
std::string url
std::string auth_header_name
std::string auth_header_value
std::chrono::seconds timeout
bool verify_ssl
bool reconnection_enabled
std::chrono::seconds reconnect_initial_delay
std::chrono::seconds reconnect_max_delay
std::atomic< bool > connected
std::atomic< bool > should_run
std::unique_ptr< std::thread > connection_thread
SSEEventCallback event_callback
SSEConnectionCallback connection_callback
std::mutex callback_mutex
Detailed Description
Definition at line 18 of file sse_client.cpp.
Constructor & Destructor Documentation
Impl()
hue4cpp::SSEClient::Impl::Impl (const std::string & endpoint_url) inline
Definition at line 41 of file sse_client.cpp.
~Impl()
hue4cpp::SSEClient::Impl::~Impl () inline
Definition at line 52 of file sse_client.cpp.
References stopConnection().
Member Function Documentation
connectionLoop()
void hue4cpp::SSEClient::Impl::connectionLoop () inline
Definition at line 124 of file sse_client.cpp.
References auth_header_name, auth_header_value, notifyConnectionChange(), notifyEvent(), parseSSELine(), reconnect_initial_delay, reconnect_max_delay, reconnection_enabled, should_run, timeout, url, and verify_ssl.
notifyConnectionChange()
void hue4cpp::SSEClient::Impl::notifyConnectionChange (bool is_connected) inline
Definition at line 63 of file sse_client.cpp.
References callback_mutex, connected, and connection_callback.
Referenced by connectionLoop().
notifyEvent()
void hue4cpp::SSEClient::Impl::notifyEvent (const SSEEvent & event) inline
Definition at line 71 of file sse_client.cpp.
References callback_mutex, and event_callback.
Referenced by connectionLoop().
parseSSELine()
bool hue4cpp::SSEClient::Impl::parseSSELine (const std::string & line, SSEEvent & current_event) inline
Parse SSE stream data.
Parameters
line Line from SSE stream
current_event Current event being built
Returns
true if event is complete, false otherwise
Definition at line 84 of file sse_client.cpp.
References hue4cpp::SSEEvent::data, hue4cpp::SSEEvent::event_type, and hue4cpp::SSEEvent::id.
Referenced by connectionLoop().
stopConnection()
void hue4cpp::SSEClient::Impl::stopConnection () inline
Definition at line 56 of file sse_client.cpp.
References connection_thread, and should_run.
Referenced by ~Impl().
Member Data Documentation
auth_header_name
std::string hue4cpp::SSEClient::Impl::auth_header_name
Definition at line 21 of file sse_client.cpp.
Referenced by connectionLoop().
auth_header_value
std::string hue4cpp::SSEClient::Impl::auth_header_value
Definition at line 22 of file sse_client.cpp.
Referenced by connectionLoop().
callback_mutex
std::mutex hue4cpp::SSEClient::Impl::callback_mutex
Definition at line 39 of file sse_client.cpp.
Referenced by notifyConnectionChange(), and notifyEvent().
connected
std::atomic<bool> hue4cpp::SSEClient::Impl::connected
Definition at line 32 of file sse_client.cpp.
Referenced by notifyConnectionChange().
connection_callback
SSEConnectionCallback hue4cpp::SSEClient::Impl::connection_callback
Definition at line 38 of file sse_client.cpp.
Referenced by notifyConnectionChange().
connection_thread
std::unique_ptr<std::thread> hue4cpp::SSEClient::Impl::connection_thread
Definition at line 34 of file sse_client.cpp.
Referenced by stopConnection().
event_callback
SSEEventCallback hue4cpp::SSEClient::Impl::event_callback
Definition at line 37 of file sse_client.cpp.
Referenced by notifyEvent().
reconnect_initial_delay
std::chrono::seconds hue4cpp::SSEClient::Impl::reconnect_initial_delay
Definition at line 28 of file sse_client.cpp.
Referenced by connectionLoop().
reconnect_max_delay
std::chrono::seconds hue4cpp::SSEClient::Impl::reconnect_max_delay
Definition at line 29 of file sse_client.cpp.
Referenced by connectionLoop().
reconnection_enabled
bool hue4cpp::SSEClient::Impl::reconnection_enabled
Definition at line 27 of file sse_client.cpp.
Referenced by connectionLoop().
should_run
std::atomic<bool> hue4cpp::SSEClient::Impl::should_run
Definition at line 33 of file sse_client.cpp.
Referenced by connectionLoop(), and stopConnection().
timeout
std::chrono::seconds hue4cpp::SSEClient::Impl::timeout
Definition at line 23 of file sse_client.cpp.
Referenced by connectionLoop().
url
std::string hue4cpp::SSEClient::Impl::url
Definition at line 20 of file sse_client.cpp.
Referenced by connectionLoop().
verify_ssl
bool hue4cpp::SSEClient::Impl::verify_ssl
Definition at line 24 of file sse_client.cpp.
Referenced by connectionLoop().
The documentation for this class was generated from the following file:
src/sse_client.cpp