hue4cpp: hue4cpp::Sensor Class Reference
hue4cpp::Sensor Class Reference abstract
Abstract base class for all Hue sensors.
#include <sensor_base.h>
Public Member Functions
virtual ~Sensor ()=default
Virtual destructor.
Sensor (const Sensor &)=delete
Sensor & operator= (const Sensor &)=delete
Sensor (Sensor &&)=delete
Sensor & operator= (Sensor &&)=delete
std::string getId () const
Compatibility helper – prefer the Id property for new code.
virtual SensorType getType () const =0
Get the sensor's type.
bool isEnabled () const
Check if sensor is enabled.
Result< void > refresh ()
Refresh sensor state from bridge.
void initFromJson (const nlohmann::json &json)
Update sensor state from JSON data.
std::string getResourceTypeString () const
Get the resource type string for this sensor (e.g., "motion", "temperature")
Public Attributes
ReactiveLitepp::ReadonlyProperty< std::string > Id
Sensor unique identifier (read-only)
ReactiveLitepp::Property< std::string > Name
Get or set the sensor's display name.
ReactiveLitepp::Event< const ResourceEventArgs & > OnStateChanged
Fired whenever the bridge reports a state change for this sensor.
Protected Member Functions
Sensor (const std::string &id, Bridge *bridge, SensorType type)
Protected constructor - only derived classes can construct.
Bridge * getBridge () const
Get the bridge pointer (for derived classes)
Protected Attributes
std::string _id
std::string _name
Bridge * _bridge
SensorType _type
Friends
class Bridge
Detailed Description
Abstract base class for all Hue sensors.
Sensors are ObservableObjects. Subscribing to OnStateChanged gives real-time property-change notifications whenever the bridge reports a new reading via SSE.
Definition at line 30 of file sensor_base.h.
Constructor & Destructor Documentation
~Sensor()
virtual hue4cpp::Sensor::~Sensor () virtual default
Virtual destructor.
Sensor() [1/3]
hue4cpp::Sensor::Sensor (const Sensor &) delete
Sensor() [2/3]
hue4cpp::Sensor::Sensor (Sensor &&) delete
Sensor() [3/3]
hue4cpp::Sensor::Sensor (const std::string & id, Bridge * bridge, SensorType type) protected
Protected constructor - only derived classes can construct.
Parameters
id Sensor unique identifier
bridge Pointer to parent bridge
type Sensor type
Definition at line 37 of file sensor_base.cpp.
Member Function Documentation
getBridge()
Bridge * hue4cpp::Sensor::getBridge () const protected
Get the bridge pointer (for derived classes)
Returns
Pointer to parent bridge (may be nullptr)
Definition at line 67 of file sensor_base.cpp.
References _bridge.
getId()
std::string hue4cpp::Sensor::getId () const inline
Compatibility helper – prefer the Id property for new code.
Returns
Sensor ID
Definition at line 76 of file sensor_base.h.
References _id.
getResourceTypeString()
std::string hue4cpp::Sensor::getResourceTypeString () const
Get the resource type string for this sensor (e.g., "motion", "temperature")
Returns
API resource type string
Definition at line 42 of file sensor_base.cpp.
References _type, hue4cpp::BellButton, hue4cpp::Button, hue4cpp::CameraMotion, hue4cpp::Geolocation, hue4cpp::LightLevel, hue4cpp::Motion, hue4cpp::RelativeRotary, hue4cpp::Tamper, and hue4cpp::Temperature.
Referenced by isEnabled(), and refresh().
getType()
virtual SensorType hue4cpp::Sensor::getType () const pure virtual
Get the sensor's type.
Returns
SensorType
Implemented in hue4cpp::BellButtonSensor, hue4cpp::ButtonSensor, hue4cpp::CameraMotionSensor, hue4cpp::GeolocationSensor, hue4cpp::LightLevelSensor, hue4cpp::MotionSensor, hue4cpp::RelativeRotarySensor, hue4cpp::TamperSensor, and hue4cpp::TemperatureSensor.
initFromJson()
void hue4cpp::Sensor::initFromJson (const nlohmann::json & json)
Update sensor state from JSON data.
Parameters
json JSON object containing sensor data from API
Note
This is an internal method used by Bridge to populate sensor data
Definition at line 117 of file sensor_base.cpp.
References _bridge, _id, _name, hue4cpp::Bridge::getStateManager(), hue4cpp::json_utils::getValue(), and hue4cpp::StateManager::setResourceState().
isEnabled()
bool hue4cpp::Sensor::isEnabled () const
Check if sensor is enabled.
Returns
true if enabled, false otherwise
Definition at line 71 of file sensor_base.cpp.
References _bridge, _id, getResourceTypeString(), hue4cpp::Bridge::getSensorState(), and hue4cpp::json_utils::parse().
operator=() [1/2]
Sensor & hue4cpp::Sensor::operator= (const Sensor &) delete
operator=() [2/2]
Sensor & hue4cpp::Sensor::operator= (Sensor &&) delete
refresh()
Result< void > hue4cpp::Sensor::refresh ()
Refresh sensor state from bridge.
Returns
Result indicating success or failure
Definition at line 103 of file sensor_base.cpp.
References _bridge, _id, getResourceTypeString(), hue4cpp::Bridge::getSensorState(), hue4cpp::InvalidParameter, and hue4cpp::NetworkError.
Friends And Related Symbol Documentation
Bridge
friend class Bridge friend
Definition at line 167 of file sensor_base.h.
Member Data Documentation
_bridge
Bridge* hue4cpp::Sensor::_bridge protected
Definition at line 137 of file sensor_base.h.
Referenced by getBridge(), initFromJson(), isEnabled(), and refresh().
_id
std::string hue4cpp::Sensor::_id protected
Definition at line 135 of file sensor_base.h.
Referenced by getId(), initFromJson(), isEnabled(), and refresh().
_name
std::string hue4cpp::Sensor::_name protected
Definition at line 136 of file sensor_base.h.
Referenced by initFromJson().
_type
SensorType hue4cpp::Sensor::_type protected
Definition at line 138 of file sensor_base.h.
Referenced by getResourceTypeString().
Id
ReactiveLitepp::ReadonlyProperty<std::string> hue4cpp::Sensor::Id
Initial value:
{
        [this]() { return _id; }
    }
Sensor unique identifier (read-only)
Definition at line 46 of file sensor_base.h.
Name
ReactiveLitepp::Property<std::string> hue4cpp::Sensor::Name
Initial value:
{
        [this]() { return _name; },
        [this](std::string& value) {
            try {
                NotifyPropertyChanging<&Sensor::Name>();
                setName(value);
                NotifyPropertyChanged<&Sensor::Name>();
            }
            catch (const HueException&) { throw; }
        }
    }
Get or set the sensor's display name.
Assigning a new value PUTs {"metadata":{"name":"\u2026"}} to the bridge immediately. The bridge confirms the rename via an SSE event which updates the backing field and fires PropertyChanged a second time.
Exceptions
InvalidParameterException if the name is empty
BridgeNotReachableException if the bridge is not available
AuthenticationException if not authenticated
Definition at line 60 of file sensor_base.h.
OnStateChanged
ReactiveLitepp::Event<const ResourceEventArgs&> hue4cpp::Sensor::OnStateChanged
Fired whenever the bridge reports a state change for this sensor.
Subscribe to be notified reactively instead of polling:
auto sub = sensor->OnStateChanged.SubscribeScoped(
    [](const ResourceEventArgs& e) { ... });
Definition at line 112 of file sensor_base.h.
The documentation for this class was generated from the following files:
include/hue4cpp/sensors/sensor_base.h
src/sensors/sensor_base.cpp