hue4cpp: hue4cpp::LightLevelSensor Class Reference
hue4cpp::LightLevelSensor Class Reference
Represents a light level sensor.
#include <light_level_sensor.h>
Public Member Functions
LightLevelSensor (const std::string &id, Bridge *bridge)
Construct a LightLevelSensor.
SensorType getType () const override
Get the sensor type.
LightLevelState getLightLevelState () const
Get current light level reading.
Public Member Functions inherited from hue4cpp::Sensor
virtual ~Sensor ()=default
Virtual destructor.
Sensor (const Sensor &)=delete
Sensor & operator= (const Sensor &)=delete
Sensor (Sensor &&) noexcept=default
Sensor & operator= (Sensor &&) noexcept=default
std::string getId () const
Get the sensor's unique identifier.
bool isEnabled () const
Check if sensor is enabled.
Result< void > refresh ()
Refresh sensor state from bridge.
void initFromJson (const nlohmann::json &json)
Update sensor state from JSON data.
Additional Inherited Members
Protected Member Functions inherited from hue4cpp::Sensor
Sensor (const std::string &id, Bridge *bridge, SensorType type)
Protected constructor - only derived classes can construct.
std::string getResourceTypeString () const
Get the resource type string for API calls.
Bridge * getBridge () const
Get the bridge pointer (for derived classes)
Protected Attributes inherited from hue4cpp::Sensor
std::string _id
Bridge * _bridge
SensorType _type
Detailed Description
Represents a light level sensor.
Light level sensors measure ambient illuminance.
Definition at line 17 of file light_level_sensor.h.
Constructor & Destructor Documentation
LightLevelSensor()
hue4cpp::LightLevelSensor::LightLevelSensor (const std::string & id, Bridge * bridge)
Construct a LightLevelSensor.
Parameters
id Sensor unique identifier
bridge Pointer to parent bridge
Definition at line 7 of file light_level_sensor.cpp.
Member Function Documentation
getLightLevelState()
LightLevelState hue4cpp::LightLevelSensor::getLightLevelState () const
Get current light level reading.
Returns
LightLevelState with illuminance measurement
Definition at line 15 of file light_level_sensor.cpp.
References hue4cpp::Sensor::getBridge(), hue4cpp::Sensor::getId(), hue4cpp::Sensor::getResourceTypeString(), hue4cpp::Bridge::getSensorState(), hue4cpp::json_utils::getValue(), hue4cpp::LightLevelState::light_level, hue4cpp::LightLevelState::light_level_valid, and hue4cpp::json_utils::parse().
getType()
SensorType hue4cpp::LightLevelSensor::getType () const override virtual
Get the sensor type.
Returns
SensorType::LightLevel
Implements hue4cpp::Sensor.
Definition at line 11 of file light_level_sensor.cpp.
References hue4cpp::LightLevel.
The documentation for this class was generated from the following files:
include/hue4cpp/sensors/light_level_sensor.h
src/sensors/light_level_sensor.cpp