hue4cpp: hue4cpp::CameraMotionSensor Class Reference
hue4cpp::CameraMotionSensor Class Reference
Represents a camera motion sensor.
#include <camera_motion_sensor.h>
Public Member Functions
CameraMotionSensor (const std::string &id, Bridge *bridge)
Construct a CameraMotionSensor.
SensorType getType () const override
Get the sensor type.
CameraMotionState getCameraMotionState () const
Get current camera motion state.
Public Member Functions inherited from hue4cpp::Sensor
virtual ~Sensor ()
Virtual destructor.
Sensor (const Sensor &)=delete
Sensor & operator= (const Sensor &)=delete
Sensor (Sensor &&) noexcept
Sensor & operator= (Sensor &&) noexcept
std::string getId () const
Get the sensor's unique identifier.
bool isEnabled () const
Check if sensor is enabled.
Result< void > refresh ()
Refresh sensor state from bridge.
void updateFromJson (const nlohmann::json &json)
Update sensor state from JSON data.
Additional Inherited Members
Protected Member Functions inherited from hue4cpp::Sensor
Sensor (const std::string &id, Bridge *bridge, SensorType type)
Protected constructor - only derived classes can construct.
std::string getResourceTypeString () const
Get the resource type string for API calls.
Bridge * getBridge () const
Get the bridge pointer (for derived classes)
Protected Attributes inherited from hue4cpp::Sensor
std::unique_ptr< Impl > pImpl
Detailed Description
Represents a camera motion sensor.
Camera motion sensors detect movement using camera vision rather than PIR.
Definition at line 17 of file camera_motion_sensor.h.
Constructor & Destructor Documentation
CameraMotionSensor()
hue4cpp::CameraMotionSensor::CameraMotionSensor (const std::string & id, Bridge * bridge)
Construct a CameraMotionSensor.
Parameters
id Sensor unique identifier
bridge Pointer to parent bridge
Definition at line 7 of file camera_motion_sensor.cpp.
Member Function Documentation
getCameraMotionState()
CameraMotionState hue4cpp::CameraMotionSensor::getCameraMotionState () const
Get current camera motion state.
Returns
CameraMotionState with motion detection status
Definition at line 15 of file camera_motion_sensor.cpp.
References hue4cpp::Sensor::getBridge(), hue4cpp::Sensor::getId(), hue4cpp::Sensor::getResourceTypeString(), hue4cpp::Bridge::getSensorState(), hue4cpp::json_utils::getValue(), hue4cpp::CameraMotionState::motion, hue4cpp::CameraMotionState::motion_valid, and hue4cpp::json_utils::parse().
getType()
SensorType hue4cpp::CameraMotionSensor::getType () const override virtual
Get the sensor type.
Returns
SensorType::CameraMotion
Implements hue4cpp::Sensor.
Definition at line 11 of file camera_motion_sensor.cpp.
References hue4cpp::CameraMotion.
The documentation for this class was generated from the following files:
include/hue4cpp/sensors/camera_motion_sensor.h
src/sensors/camera_motion_sensor.cpp