hue4cpp: hue4cpp::Bridge Class Reference
hue4cpp::Bridge Class Reference
Represents a Philips Hue Bridge.
#include <bridge.h>
Public Member Functions
Bridge ()
Default constructor.
Bridge (const BridgeInfo &info)
Construct a Bridge with known connection info.
~Bridge ()
Destructor.
Bridge (const Bridge &)=delete
Bridge & operator= (const Bridge &)=delete
Bridge (Bridge &&) noexcept
Bridge & operator= (Bridge &&) noexcept
Result< std::string > authenticate (const std::string &app_name, const std::string &device_name="")
Authenticate with the bridge.
void setAuthenticationKey (const std::string &key)
Set authentication key for the bridge.
std::string getAuthenticationKey () const
Get the current authentication key.
bool isAuthenticated () const
Check if bridge is authenticated.
Result< void > validateAuthentication () const
Validate the current authentication key with the bridge.
std::vector< std::unique_ptr< Light > > getLights ()
Get all lights connected to this bridge.
std::unique_ptr< Light > getLight (const std::string &light_id)
Get a specific light by ID.
std::vector< std::unique_ptr< Sensor > > getSensors ()
Get all sensors connected to this bridge.
std::unique_ptr< Sensor > getSensor (const std::string &sensor_id)
Get a specific sensor by ID.
std::vector< std::unique_ptr< MotionSensor > > getMotionSensors ()
Get all motion sensors.
std::vector< std::unique_ptr< TemperatureSensor > > getTemperatureSensors ()
Get all temperature sensors.
std::vector< std::unique_ptr< LightLevelSensor > > getLightLevelSensors ()
Get all light level sensors.
std::vector< std::unique_ptr< ButtonSensor > > getButtonSensors ()
Get all button sensors.
std::vector< std::unique_ptr< CameraMotionSensor > > getCameraMotionSensors ()
Get all camera motion sensors.
std::vector< std::unique_ptr< BellButtonSensor > > getBellButtonSensors ()
Get all bell button sensors (doorbells)
std::vector< std::unique_ptr< RelativeRotarySensor > > getRelativeRotarySensors ()
Get all relative rotary sensors (dials/knobs)
std::vector< std::unique_ptr< GeolocationSensor > > getGeolocationSensors ()
Get all geolocation sensors.
std::vector< std::unique_ptr< TamperSensor > > getTamperSensors ()
Get all tamper detection sensors.
void setInfo (const BridgeInfo &info)
Set the bridge information.
const BridgeInfo & getInfo () const
Get bridge information.
StateManager & getStateManager ()
Get the state manager for this bridge.
std::string getLightState (const std::string &light_id, bool refreshCache)
Get light state (cache-first, API-fallback)
std::string getSensorState (const std::string &sensor_id, const std::string &sensor_type, bool refreshCache)
Get sensor state (cache-first, API-fallback)
bool isReachable () const
Check if the bridge is reachable.
Static Public Member Functions
static std::vector< Bridge > discover ()
Discover Hue bridges on the local network.
static std::vector< Bridge > discoverMDNS ()
Discover bridges using mDNS.
static std::vector< Bridge > discoverNUPnP ()
Discover bridges using N-UPnP (broker-based)
Detailed Description
Represents a Philips Hue Bridge.
The Bridge class is the main entry point for interacting with a Hue system. It handles discovery, authentication, and provides access to lights and other resources.
Definition at line 35 of file bridge.h.
Constructor & Destructor Documentation
Bridge() [1/4]
hue4cpp::Bridge::Bridge ()
Default constructor.
Definition at line 20 of file bridge.cpp.
Bridge() [2/4]
hue4cpp::Bridge::Bridge (const BridgeInfo & info) explicit
Construct a Bridge with known connection info.
Parameters
info Bridge connection information
Definition at line 22 of file bridge.cpp.
~Bridge()
hue4cpp::Bridge::~Bridge ()
Destructor.
Definition at line 25 of file bridge.cpp.
Bridge() [3/4]
hue4cpp::Bridge::Bridge (const Bridge &) delete
Bridge() [4/4]
hue4cpp::Bridge::Bridge (Bridge && other) noexcept
Definition at line 31 of file bridge.cpp.
Member Function Documentation
authenticate()
Result< std::string > hue4cpp::Bridge::authenticate (const std::string & app_name, const std::string & device_name = "")
Authenticate with the bridge.
Parameters
app_name Name of the application
device_name Name of the device (optional)
Returns
Result indicating success or failure
Definition at line 53 of file bridge.cpp.
References hue4cpp::AuthenticationFailed, hue4cpp::json_utils::getValue(), hue4cpp::InvalidParameter, hue4cpp::InvalidRequest, hue4cpp::BridgeInfo::ip_address, hue4cpp::NetworkError, hue4cpp::json_utils::parse(), hue4cpp::HttpClient::post(), hue4cpp::HttpClient::setTimeout(), hue4cpp::HttpClient::setVerifySsl(), hue4cpp::TimeoutError, hue4cpp::json_utils::toString(), and hue4cpp::UnknownError.
discover()
std::vector< Bridge > hue4cpp::Bridge::discover () static
Discover Hue bridges on the local network.
Returns
Vector of discovered bridges
Definition at line 381 of file discovery.cpp.
References discoverMDNS(), and discoverNUPnP().
discoverMDNS()
std::vector< Bridge > hue4cpp::Bridge::discoverMDNS () static
Discover bridges using mDNS.
Returns
Vector of discovered bridges
Definition at line 226 of file discovery.cpp.
References hue4cpp::BridgeInfo::id, hue4cpp::BridgeInfo::ip_address, and service_name.
Referenced by discover().
discoverNUPnP()
std::vector< Bridge > hue4cpp::Bridge::discoverNUPnP () static
Discover bridges using N-UPnP (broker-based)
Returns
Vector of discovered bridges
Definition at line 333 of file discovery.cpp.
References hue4cpp::HttpClient::get(), hue4cpp::json_utils::getValue(), hue4cpp::BridgeInfo::id, hue4cpp::BridgeInfo::ip_address, hue4cpp::BridgeInfo::name, and hue4cpp::json_utils::parse().
Referenced by discover().
getAuthenticationKey()
std::string hue4cpp::Bridge::getAuthenticationKey () const
Get the current authentication key.
Returns
The authentication key, or empty string if not authenticated
Definition at line 165 of file bridge.cpp.
Referenced by hue4cpp::StateManager::start().
getBellButtonSensors()
std::vector< std::unique_ptr< BellButtonSensor > > hue4cpp::Bridge::getBellButtonSensors ()
Get all bell button sensors (doorbells)
Returns
Vector of unique pointers to BellButtonSensor objects
Definition at line 684 of file bridge.cpp.
References isAuthenticated().
Referenced by getSensors().
getButtonSensors()
std::vector< std::unique_ptr< ButtonSensor > > hue4cpp::Bridge::getButtonSensors ()
Get all button sensors.
Returns
Vector of unique pointers to ButtonSensor objects
Definition at line 670 of file bridge.cpp.
References isAuthenticated().
Referenced by getSensors().
getCameraMotionSensors()
std::vector< std::unique_ptr< CameraMotionSensor > > hue4cpp::Bridge::getCameraMotionSensors ()
Get all camera motion sensors.
Returns
Vector of unique pointers to CameraMotionSensor objects
Definition at line 677 of file bridge.cpp.
References isAuthenticated().
Referenced by getSensors().
getGeolocationSensors()
std::vector< std::unique_ptr< GeolocationSensor > > hue4cpp::Bridge::getGeolocationSensors ()
Get all geolocation sensors.
Returns
Vector of unique pointers to GeolocationSensor objects
Definition at line 698 of file bridge.cpp.
References isAuthenticated().
Referenced by getSensors().
getInfo()
const BridgeInfo & hue4cpp::Bridge::getInfo () const
Get bridge information.
Returns
BridgeInfo structure
Definition at line 354 of file bridge.cpp.
Referenced by isReachable(), and hue4cpp::StateManager::start().
getLight()
std::unique_ptr< Light > hue4cpp::Bridge::getLight (const std::string & light_id)
Get a specific light by ID.
Parameters
light_id The unique identifier of the light
Returns
Unique pointer to Light object (nullptr if not found)
Definition at line 298 of file bridge.cpp.
References hue4cpp::HttpClient::get(), hue4cpp::BridgeInfo::ip_address, isAuthenticated(), hue4cpp::json_utils::parse(), hue4cpp::HttpClient::setTimeout(), and hue4cpp::HttpClient::setVerifySsl().
Referenced by hue4cpp::Light::refresh().
getLightLevelSensors()
std::vector< std::unique_ptr< LightLevelSensor > > hue4cpp::Bridge::getLightLevelSensors ()
Get all light level sensors.
Returns
Vector of unique pointers to LightLevelSensor objects
Definition at line 663 of file bridge.cpp.
References isAuthenticated().
Referenced by getSensors().
getLights()
std::vector< std::unique_ptr< Light > > hue4cpp::Bridge::getLights ()
Get all lights connected to this bridge.
Returns
Vector of Light objects
Definition at line 237 of file bridge.cpp.
References hue4cpp::HttpClient::get(), hue4cpp::json_utils::getValue(), hue4cpp::BridgeInfo::ip_address, isAuthenticated(), hue4cpp::json_utils::parse(), hue4cpp::HttpClient::setTimeout(), and hue4cpp::HttpClient::setVerifySsl().
getLightState()
std::string hue4cpp::Bridge::getLightState (const std::string & light_id, bool refreshCache)
Get light state (cache-first, API-fallback)
Parameters
light_id The unique identifier of the light
refreshCache If true, forces fetching the complete state from the bridge API
Returns
JSON string with light state, or empty if not found
Definition at line 362 of file bridge.cpp.
References hue4cpp::HttpClient::get(), hue4cpp::BridgeInfo::ip_address, isAuthenticated(), hue4cpp::json_utils::parse(), hue4cpp::HttpClient::setTimeout(), and hue4cpp::HttpClient::setVerifySsl().
getMotionSensors()
std::vector< std::unique_ptr< MotionSensor > > hue4cpp::Bridge::getMotionSensors ()
Get all motion sensors.
Returns
Vector of unique pointers to MotionSensor objects
Definition at line 649 of file bridge.cpp.
References isAuthenticated().
Referenced by getSensors().
getRelativeRotarySensors()
std::vector< std::unique_ptr< RelativeRotarySensor > > hue4cpp::Bridge::getRelativeRotarySensors ()
Get all relative rotary sensors (dials/knobs)
Returns
Vector of unique pointers to RelativeRotarySensor objects
Definition at line 691 of file bridge.cpp.
References isAuthenticated().
Referenced by getSensors().
getSensor()
std::unique_ptr< Sensor > hue4cpp::Bridge::getSensor (const std::string & sensor_id)
Get a specific sensor by ID.
Parameters
sensor_id The unique identifier of the sensor
Returns
Unique pointer to Sensor object (nullptr if not found)
Definition at line 532 of file bridge.cpp.
References hue4cpp::createSensorFromJson(), hue4cpp::HttpClient::get(), hue4cpp::BridgeInfo::ip_address, isAuthenticated(), hue4cpp::json_utils::parse(), hue4cpp::HttpClient::setTimeout(), and hue4cpp::HttpClient::setVerifySsl().
getSensors()
std::vector< std::unique_ptr< Sensor > > hue4cpp::Bridge::getSensors ()
Get all sensors connected to this bridge.
Returns
Vector of unique pointers to Sensor objects
Definition at line 486 of file bridge.cpp.
References getBellButtonSensors(), getButtonSensors(), getCameraMotionSensors(), getGeolocationSensors(), getLightLevelSensors(), getMotionSensors(), getRelativeRotarySensors(), getTamperSensors(), and getTemperatureSensors().
getSensorState()
std::string hue4cpp::Bridge::getSensorState (const std::string & sensor_id, const std::string & sensor_type, bool refreshCache)
Get sensor state (cache-first, API-fallback)
Parameters
sensor_id The unique identifier of the sensor
sensor_type The type of sensor (motion, temperature, light_level, button)
refreshCache If true, forces fetching the complete state from the bridge API
Returns
JSON string with sensor state, or empty if not found
Definition at line 424 of file bridge.cpp.
References hue4cpp::HttpClient::get(), hue4cpp::BridgeInfo::ip_address, isAuthenticated(), hue4cpp::json_utils::parse(), hue4cpp::HttpClient::setTimeout(), and hue4cpp::HttpClient::setVerifySsl().
Referenced by hue4cpp::Sensor::isEnabled(), and hue4cpp::Sensor::refresh().
getStateManager()
StateManager & hue4cpp::Bridge::getStateManager ()
Get the state manager for this bridge.
Returns
Reference to StateManager
Definition at line 358 of file bridge.cpp.
Referenced by hue4cpp::Light::initFromJson(), and hue4cpp::Sensor::initFromJson().
getTamperSensors()
std::vector< std::unique_ptr< TamperSensor > > hue4cpp::Bridge::getTamperSensors ()
Get all tamper detection sensors.
Returns
Vector of unique pointers to TamperSensor objects
Definition at line 705 of file bridge.cpp.
References isAuthenticated().
Referenced by getSensors().
getTemperatureSensors()
std::vector< std::unique_ptr< TemperatureSensor > > hue4cpp::Bridge::getTemperatureSensors ()
Get all temperature sensors.
Returns
Vector of unique pointers to TemperatureSensor objects
Definition at line 656 of file bridge.cpp.
References isAuthenticated().
Referenced by getSensors().
isAuthenticated()
bool hue4cpp::Bridge::isAuthenticated () const
Check if bridge is authenticated.
Returns
true if authenticated, false otherwise
Definition at line 169 of file bridge.cpp.
Referenced by getBellButtonSensors(), getButtonSensors(), getCameraMotionSensors(), getGeolocationSensors(), getLight(), getLightLevelSensors(), getLights(), getLightState(), getMotionSensors(), getRelativeRotarySensors(), getSensor(), getSensorState(), getTamperSensors(), getTemperatureSensors(), and hue4cpp::Light::refresh().
isReachable()
bool hue4cpp::Bridge::isReachable () const
Check if the bridge is reachable.
Returns
true if reachable, false otherwise
Definition at line 410 of file discovery.cpp.
References hue4cpp::HttpClient::get(), getInfo(), hue4cpp::HttpResponse::isSuccess(), hue4cpp::HttpClient::setTimeout(), and hue4cpp::HttpClient::setVerifySsl().
operator=() [1/2]
Bridge & hue4cpp::Bridge::operator= (Bridge && other) noexcept
Definition at line 41 of file bridge.cpp.
operator=() [2/2]
Bridge & hue4cpp::Bridge::operator= (const Bridge &) delete
setAuthenticationKey()
void hue4cpp::Bridge::setAuthenticationKey (const std::string & key)
Set authentication key for the bridge.
Parameters
key Previously obtained authentication key
Definition at line 160 of file bridge.cpp.
setInfo()
void hue4cpp::Bridge::setInfo (const BridgeInfo & info)
Set the bridge information.
Parameters
info BridgeInfo structure
Definition at line 349 of file bridge.cpp.
validateAuthentication()
Result< void > hue4cpp::Bridge::validateAuthentication () const
Validate the current authentication key with the bridge.
Returns
Result indicating if the key is valid
Definition at line 173 of file bridge.cpp.
References hue4cpp::AuthenticationFailed, hue4cpp::AuthenticationRequired, hue4cpp::HttpClient::get(), hue4cpp::json_utils::getValue(), hue4cpp::InvalidParameter, hue4cpp::BridgeInfo::ip_address, hue4cpp::NetworkError, hue4cpp::json_utils::parse(), hue4cpp::HttpClient::setTimeout(), hue4cpp::HttpClient::setVerifySsl(), and hue4cpp::UnknownError.
The documentation for this class was generated from the following files:
include/hue4cpp/bridge.h
src/bridge.cpp
src/discovery.cpp