hue4cpp: hue4cpp::StateManager Class Reference
hue4cpp::StateManager Class Reference
Manages state synchronization via Server-Sent Events.
#include <state.h>
Public Member Functions
StateManager ()
Default constructor.
StateManager (Bridge *bridge)
Construct with parent bridge.
~StateManager ()
Destructor.
StateManager (const StateManager &)=delete
StateManager & operator= (const StateManager &)=delete
StateManager (StateManager &&) noexcept
StateManager & operator= (StateManager &&) noexcept
Result< void > start ()
Start listening for SSE events.
void stop ()
Stop listening for SSE events.
bool isRunning () const
Check if state manager is running.
std::string getResourceState (const std::string &resource_id) const
Get the current state of any resource (generic)
void setResourceState (const std::string &resource_id, const std::string &state_json)
Update resource state (replaces entire state, used for API calls)
void updateFromEvent (const std::string &event_json)
Update internal state from JSON event.
void setBridge (Bridge *bridge)
Set the parent bridge.
void clearCache ()
Clear all cached resource states.
Public Attributes
ReactiveLitepp::Event< const ResourceEventArgs & > OnResourceEvent
Single unified event fired for every resource change.
Detailed Description
Manages state synchronization via Server-Sent Events.
The StateManager maintains an up-to-date view of the bridge state by listening to SSE events from the bridge.
Definition at line 140 of file state.h.
Constructor & Destructor Documentation
StateManager() [1/4]
hue4cpp::StateManager::StateManager ()
Default constructor.
Definition at line 11 of file state.cpp.
StateManager() [2/4]
hue4cpp::StateManager::StateManager (Bridge * bridge) explicit
Construct with parent bridge.
Parameters
bridge Pointer to parent bridge
Definition at line 15 of file state.cpp.
~StateManager()
hue4cpp::StateManager::~StateManager ()
Destructor.
Definition at line 19 of file state.cpp.
References stop().
StateManager() [3/4]
hue4cpp::StateManager::StateManager (const StateManager &) delete
StateManager() [4/4]
hue4cpp::StateManager::StateManager (StateManager && other) noexcept
Definition at line 23 of file state.cpp.
Member Function Documentation
clearCache()
void hue4cpp::StateManager::clearCache ()
Clear all cached resource states.
Definition at line 250 of file state.cpp.
Referenced by start().
getResourceState()
std::string hue4cpp::StateManager::getResourceState (const std::string & resource_id) const
Get the current state of any resource (generic)
Parameters
resource_id Resource unique identifier
Returns
JSON string representing resource state, or empty if not found
Definition at line 133 of file state.cpp.
isRunning()
bool hue4cpp::StateManager::isRunning () const
Check if state manager is running.
Returns
true if running, false otherwise
Definition at line 129 of file state.cpp.
Referenced by setResourceState().
operator=() [1/2]
StateManager & hue4cpp::StateManager::operator= (const StateManager &) delete
operator=() [2/2]
StateManager & hue4cpp::StateManager::operator= (StateManager && other) noexcept
Definition at line 31 of file state.cpp.
setBridge()
void hue4cpp::StateManager::setBridge (Bridge * bridge)
Set the parent bridge.
Parameters
bridge Pointer to parent bridge
Definition at line 246 of file state.cpp.
setResourceState()
void hue4cpp::StateManager::setResourceState (const std::string & resource_id, const std::string & state_json)
Update resource state (replaces entire state, used for API calls)
Parameters
resource_id Resource unique identifier
state_json JSON string representing complete resource state
Definition at line 146 of file state.cpp.
References isRunning(), hue4cpp::LightStateChanged, OnResourceEvent, hue4cpp::SensorStateChanged, start(), and hue4cpp::Unknown.
Referenced by hue4cpp::Light::initFromJson(), and hue4cpp::Sensor::initFromJson().
start()
Result< void > hue4cpp::StateManager::start ()
Start listening for SSE events.
Returns
Result indicating success or failure
Definition at line 62 of file state.cpp.
References hue4cpp::AuthenticationRequired, hue4cpp::BridgeConnected, hue4cpp::BridgeDisconnected, clearCache(), hue4cpp::Bridge::getAuthenticationKey(), hue4cpp::Bridge::getInfo(), hue4cpp::InvalidRequest, OnResourceEvent, and updateFromEvent().
Referenced by setResourceState().
stop()
void hue4cpp::StateManager::stop ()
Stop listening for SSE events.
Definition at line 116 of file state.cpp.
Referenced by ~StateManager().
updateFromEvent()
void hue4cpp::StateManager::updateFromEvent (const std::string & event_json)
Update internal state from JSON event.
Parameters
event_json JSON event data from SSE
Definition at line 174 of file state.cpp.
References hue4cpp::LightAdded, hue4cpp::LightRemoved, hue4cpp::LightStateChanged, OnResourceEvent, hue4cpp::SensorAdded, hue4cpp::SensorRemoved, and hue4cpp::SensorStateChanged.
Referenced by start().
Member Data Documentation
OnResourceEvent
ReactiveLitepp::Event<const ResourceEventArgs&> hue4cpp::StateManager::OnResourceEvent
Single unified event fired for every resource change.
Covers lights (added / changed / removed), sensors (added / changed / removed) and bridge connectivity changes. Use ResourceEventArgs::type or the helper predicates (isLightEvent, isSensorEvent, isBridgeEvent) to filter the events you care about.
auto sub = state_manager.OnResourceEvent.SubscribeScoped(
    [](const ResourceEventArgs& e) {
        if (e.isLightEvent())   { ... }
        if (e.isSensorEvent())  { ... }
        if (e.isBridgeEvent())  { ... }
    });
Definition at line 185 of file state.h.
Referenced by setResourceState(), start(), and updateFromEvent().
The documentation for this class was generated from the following files:
include/hue4cpp/state.h
src/state.cpp