hue4cpp: hue4cpp::Light::Impl Class Reference
hue4cpp::Light::Impl Class Reference
Public Member Functions
Impl ()
Impl (const std::string &light_id, Bridge *parent_bridge)
Result< void > sendUpdate (const nlohmann::json &state_update)
void addTransitionTime (nlohmann::json &update, TransitionTime transition)
Public Attributes
std::string id
std::string name
Bridge * bridge
LightCapabilities capabilities
Detailed Description
Definition at line 16 of file light.cpp.
Constructor & Destructor Documentation
Impl() [1/2]
hue4cpp::Light::Impl::Impl () inline
Definition at line 23 of file light.cpp.
References hue4cpp::LightCapabilities::brightness, capabilities, hue4cpp::LightCapabilities::color, hue4cpp::LightCapabilities::color_temperature, hue4cpp::LightCapabilities::effects, and hue4cpp::LightCapabilities::on_off.
Impl() [2/2]
hue4cpp::Light::Impl::Impl (const std::string & light_id, Bridge * parent_bridge) inline
Definition at line 31 of file light.cpp.
References hue4cpp::LightCapabilities::brightness, capabilities, hue4cpp::LightCapabilities::color, hue4cpp::LightCapabilities::color_temperature, hue4cpp::LightCapabilities::effects, and hue4cpp::LightCapabilities::on_off.
Member Function Documentation
addTransitionTime()
void hue4cpp::Light::Impl::addTransitionTime (nlohmann::json & update, TransitionTime transition) inline
Definition at line 102 of file light.cpp.
sendUpdate()
Result< void > hue4cpp::Light::Impl::sendUpdate (const nlohmann::json & state_update) inline
Definition at line 41 of file light.cpp.
References hue4cpp::AuthenticationFailed, hue4cpp::AuthenticationRequired, bridge, hue4cpp::Bridge::getAuthenticationKey(), hue4cpp::Bridge::getInfo(), hue4cpp::json_utils::getValue(), id, hue4cpp::InvalidParameter, hue4cpp::InvalidRequest, hue4cpp::Bridge::isAuthenticated(), hue4cpp::NetworkError, hue4cpp::json_utils::parse(), hue4cpp::HttpClient::put(), hue4cpp::HttpClient::setTimeout(), hue4cpp::HttpClient::setVerifySsl(), hue4cpp::json_utils::toString(), and hue4cpp::UnknownError.
Member Data Documentation
bridge
Bridge* hue4cpp::Light::Impl::bridge
Definition at line 20 of file light.cpp.
Referenced by sendUpdate().
capabilities
LightCapabilities hue4cpp::Light::Impl::capabilities
Definition at line 21 of file light.cpp.
Referenced by Impl(), and Impl().
id
std::string hue4cpp::Light::Impl::id
Definition at line 18 of file light.cpp.
Referenced by sendUpdate().
name
std::string hue4cpp::Light::Impl::name
Definition at line 19 of file light.cpp.
The documentation for this class was generated from the following file:
src/light.cpp