hue4cpp: hue4cpp::HttpClient Class Reference
hue4cpp::HttpClient Class Reference
HTTP client for making requests to the Hue bridge.
#include <http_client.h>
Classes
class Impl
Public Member Functions
HttpClient ()
Default constructor.
~HttpClient ()
Destructor.
HttpClient (const HttpClient &)=delete
HttpClient & operator= (const HttpClient &)=delete
HttpClient (HttpClient &&) noexcept
HttpClient & operator= (HttpClient &&) noexcept
void setTimeout (std::chrono::milliseconds timeout)
Set request timeout.
void setVerifySsl (bool verify)
Set whether to verify SSL certificates.
HttpResponse get (const std::string &url, const std::map< std::string, std::string > &headers={})
Perform HTTP GET request.
HttpResponse post (const std::string &url, const std::string &body, const std::map< std::string, std::string > &headers={})
Perform HTTP POST request.
HttpResponse put (const std::string &url, const std::string &body, const std::map< std::string, std::string > &headers={})
Perform HTTP PUT request.
HttpResponse del (const std::string &url, const std::map< std::string, std::string > &headers={})
Perform HTTP DELETE request.
Detailed Description
HTTP client for making requests to the Hue bridge.
This class wraps the cpr library to provide a simplified interface for making HTTPS requests to the Hue bridge API.
Definition at line 40 of file http_client.h.
Constructor & Destructor Documentation
HttpClient() [1/3]
hue4cpp::HttpClient::HttpClient ()
Default constructor.
Definition at line 55 of file http_client.cpp.
~HttpClient()
hue4cpp::HttpClient::~HttpClient () default
Destructor.
HttpClient() [2/3]
hue4cpp::HttpClient::HttpClient (const HttpClient &) delete
HttpClient() [3/3]
hue4cpp::HttpClient::HttpClient (HttpClient &&) default noexcept
Member Function Documentation
del()
HttpResponse hue4cpp::HttpClient::del (const std::string & url, const std::map< std::string, std::string > & headers = {})
Perform HTTP DELETE request.
Parameters
url The URL to request
headers Optional headers to include in the request
Returns
HttpResponse containing the result
Definition at line 133 of file http_client.cpp.
get()
HttpResponse hue4cpp::HttpClient::get (const std::string & url, const std::map< std::string, std::string > & headers = {})
Perform HTTP GET request.
Parameters
url The URL to request
headers Optional headers to include in the request
Returns
HttpResponse containing the result
Definition at line 70 of file http_client.cpp.
Referenced by hue4cpp::Bridge::discoverNUPnP(), hue4cpp::Bridge::Impl::fetchSensorsByType(), hue4cpp::Bridge::getLight(), hue4cpp::Bridge::getLights(), hue4cpp::Bridge::getLightState(), hue4cpp::Bridge::getSensor(), hue4cpp::Bridge::getSensorState(), hue4cpp::Bridge::isReachable(), and hue4cpp::Bridge::validateAuthentication().
operator=() [1/2]
HttpClient & hue4cpp::HttpClient::operator= (const HttpClient &) delete
operator=() [2/2]
HttpClient & hue4cpp::HttpClient::operator= (HttpClient &&) default noexcept
post()
HttpResponse hue4cpp::HttpClient::post (const std::string & url, const std::string & body, const std::map< std::string, std::string > & headers = {})
Perform HTTP POST request.
Parameters
url The URL to request
body The request body (typically JSON)
headers Optional headers to include in the request
Returns
HttpResponse containing the result
Definition at line 89 of file http_client.cpp.
Referenced by hue4cpp::Bridge::authenticate().
put()
HttpResponse hue4cpp::HttpClient::put (const std::string & url, const std::string & body, const std::map< std::string, std::string > & headers = {})
Perform HTTP PUT request.
Parameters
url The URL to request
body The request body (typically JSON)
headers Optional headers to include in the request
Returns
HttpResponse containing the result
Definition at line 111 of file http_client.cpp.
Referenced by hue4cpp::Light::Impl::sendUpdate().
setTimeout()
void hue4cpp::HttpClient::setTimeout (std::chrono::milliseconds timeout)
Set request timeout.
Parameters
timeout Timeout duration in milliseconds
Definition at line 62 of file http_client.cpp.
Referenced by hue4cpp::Bridge::authenticate(), hue4cpp::Bridge::Impl::fetchSensorsByType(), hue4cpp::Bridge::getLight(), hue4cpp::Bridge::getLights(), hue4cpp::Bridge::getLightState(), hue4cpp::Bridge::getSensor(), hue4cpp::Bridge::getSensorState(), hue4cpp::Bridge::isReachable(), hue4cpp::Light::Impl::sendUpdate(), and hue4cpp::Bridge::validateAuthentication().
setVerifySsl()
void hue4cpp::HttpClient::setVerifySsl (bool verify)
Set whether to verify SSL certificates.
Parameters
verify true to verify certificates (default), false to skip verification
Note
For production use, verification should be enabled
Definition at line 66 of file http_client.cpp.
Referenced by hue4cpp::Bridge::authenticate(), hue4cpp::Bridge::Impl::fetchSensorsByType(), hue4cpp::Bridge::getLight(), hue4cpp::Bridge::getLights(), hue4cpp::Bridge::getLightState(), hue4cpp::Bridge::getSensor(), hue4cpp::Bridge::getSensorState(), hue4cpp::Bridge::isReachable(), hue4cpp::Light::Impl::sendUpdate(), and hue4cpp::Bridge::validateAuthentication().
The documentation for this class was generated from the following files:
include/hue4cpp/http_client.h
src/http_client.cpp