hue4cpp: hue4cpp::Light Class Reference
hue4cpp::Light Class Reference
From state.h - forward declared to avoid circular includes.
#include <light.h>
Public Member Functions
Light ()
Default constructor.
Light (const std::string &id, Bridge *bridge)
Construct a Light with ID and parent bridge.
~Light ()=default
Destructor.
Light (const Light &)=delete
Light & operator= (const Light &)=delete
Light (Light &&)=delete
Light & operator= (Light &&)=delete
LightCapabilities getCapabilities () const
Get the light's capabilities.
void refresh ()
Refresh light state from bridge.
void initFromJson (const nlohmann::json &json)
Initialize light state from JSON data.
Public Attributes
ReadonlyProperty< std::string > Id
Get the light's unique identifier.
Property< std::string > Name
Get or set the light's display name.
Property< TransitionTime > TransitionTime_
Get or set the transition time for light changes.
Property< bool > IsOn
Get or set the on/off state.
Property< uint8_t > Brightness
Get or set the brightness level.
Property< XYColor > XYColor_
Get or set the color in XY color space.
Property< RGBColor > RGBColor_
Get or set the color in RGB color space.
Property< ColorTemperature > ColorTemperature_
Get or set the color temperature.
Friends
class Bridge
Detailed Description
From state.h - forward declared to avoid circular includes.
Represents a single Hue light
The Light class provides control of individual lights through observable properties including power state, brightness, color, and effects. All control operations are performed through the public properties, which handle exceptions appropriately.
Exceptions
ResourceNotFoundException if light data is not available
InvalidParameterException if invalid parameters are provided
BridgeNotReachableException if bridge cannot be accessed
Definition at line 34 of file light.h.
Constructor & Destructor Documentation
Light() [1/4]
hue4cpp::Light::Light ()
Default constructor.
Definition at line 20 of file light.cpp.
References hue4cpp::LightCapabilities::brightness, hue4cpp::LightCapabilities::color, hue4cpp::LightCapabilities::color_temperature, hue4cpp::LightCapabilities::effects, and hue4cpp::LightCapabilities::on_off.
Light() [2/4]
hue4cpp::Light::Light (const std::string & id, Bridge * bridge)
Construct a Light with ID and parent bridge.
Parameters
id Light unique identifier
bridge Pointer to parent bridge
Definition at line 29 of file light.cpp.
References hue4cpp::LightCapabilities::brightness, hue4cpp::LightCapabilities::color, hue4cpp::LightCapabilities::color_temperature, hue4cpp::LightCapabilities::effects, and hue4cpp::LightCapabilities::on_off.
~Light()
hue4cpp::Light::~Light () default
Destructor.
Light() [3/4]
hue4cpp::Light::Light (const Light &) delete
Light() [4/4]
hue4cpp::Light::Light (Light &&) delete
Member Function Documentation
getCapabilities()
LightCapabilities hue4cpp::Light::getCapabilities () const
Get the light's capabilities.
Returns
LightCapabilities structure
Definition at line 39 of file light.cpp.
initFromJson()
void hue4cpp::Light::initFromJson (const nlohmann::json & json)
Initialize light state from JSON data.
Parameters
json JSON object containing light data from API
Note
This is an internal method used by Bridge to populate light data
Definition at line 395 of file light.cpp.
References hue4cpp::LightCapabilities::brightness, hue4cpp::LightCapabilities::color, hue4cpp::LightCapabilities::color_temperature, hue4cpp::LightCapabilities::effects, hue4cpp::Bridge::getStateManager(), hue4cpp::json_utils::getValue(), hue4cpp::LightCapabilities::on_off, and hue4cpp::StateManager::setResourceState().
operator=() [1/2]
Light & hue4cpp::Light::operator= (const Light &) delete
operator=() [2/2]
Light & hue4cpp::Light::operator= (Light &&) delete
refresh()
void hue4cpp::Light::refresh ()
Refresh light state from bridge.
Exceptions
BridgeNotReachableException if bridge is not available
ResourceNotFoundException if light cannot be found
AuthenticationException if not authenticated
Definition at line 377 of file light.cpp.
References hue4cpp::Bridge::getLight(), and hue4cpp::Bridge::isAuthenticated().
Friends And Related Symbol Documentation
Bridge
friend class Bridge friend
Definition at line 319 of file light.h.
Member Data Documentation
Brightness
Property<uint8_t> hue4cpp::Light::Brightness
Initial value:
{
            [this]() {
                try {
                    return getBrightness();
                }
                catch (const HueException&) {
                    throw;
                }
            },
            [this](uint8_t& value) {
                try {
                    NotifyPropertyChanging<&Light::Brightness>();
                    setBrightness(value);
                }
                catch (const HueException&) {
                    throw;
                }
            }
        }
Get or set the brightness level.
Exceptions
ResourceNotFoundException if brightness is not available
InvalidParameterException if brightness is out of range or not supported
BridgeNotReachableException if bridge is not available
AuthenticationException if not authenticated
Definition at line 160 of file light.h.
ColorTemperature_
Property<ColorTemperature> hue4cpp::Light::ColorTemperature_
Initial value:
{
            [this]() {
                try {
                    return getColorTemperature();
                }
                catch (const HueException&) {
                    throw;
                }
            },
            [this](ColorTemperature& value) {
                try {
                    NotifyPropertyChanging<&Light::ColorTemperature_>();
                    setColorTemperature(value);
                }
                catch (const HueException&) {
                    throw;
                }
            }
        }
Get or set the color temperature.
Exceptions
ResourceNotFoundException if color temperature is not available
InvalidParameterException if temperature is invalid or not supported
BridgeNotReachableException if bridge is not available
AuthenticationException if not authenticated
Definition at line 244 of file light.h.
Id
ReadonlyProperty<std::string> hue4cpp::Light::Id
Initial value:
{
            [this]() {
                    return _id;
            }
        }
Get the light's unique identifier.
Returns
Light ID
Definition at line 63 of file light.h.
IsOn
Property<bool> hue4cpp::Light::IsOn
Initial value:
{
            [this]() {
                try {
                    return isOn();
                }
                catch (const HueException&) {
                    throw;
                }
            },
            [this](bool& value) {
                try {
                    NotifyPropertyChanging<&Light::IsOn>();
                    value ? turnOn() : turnOff();
                }
                catch (const HueException&) {
                    throw;
                }
            }
        }
Get or set the on/off state.
Exceptions
BridgeNotReachableException if bridge is not available
InvalidParameterException if light does not support on/off
AuthenticationException if not authenticated
ResourceNotFoundException if state is not available
Definition at line 132 of file light.h.
Name
Property<std::string> hue4cpp::Light::Name
Initial value:
{
            [this]() { return _name; },
            [this](std::string& value) {
                try {
                    NotifyPropertyChanging<&Light::Name>();
                    setName(value);
                    NotifyPropertyChanged<&Light::Name>();
                }
                catch (const HueException&) { throw; }
            }
        }
Get or set the light's display name.
Assigning a new value PUTs {"metadata":{"name":"…"}} to the bridge immediately. The bridge confirms the rename via an SSE event, which updates the backing field and fires PropertyChanged a second time.
Exceptions
InvalidParameterException if the name is empty
BridgeNotReachableException if the bridge is not available
AuthenticationException if not authenticated
Definition at line 79 of file light.h.
RGBColor_
Property<RGBColor> hue4cpp::Light::RGBColor_
Initial value:
{
            [this]() {
                try {
                    return color_utils::xyToRgb(getColor());
                }
                catch (const HueException&) {
                    throw;
                }
            },
            [this](RGBColor& value) {
                try {
                    NotifyPropertyChanging<&Light::RGBColor_>();
                    setColor(value);
                }
                catch (const HueException&) {
                    throw;
                }
            }
        }
Get or set the color in RGB color space.
Exceptions
ResourceNotFoundException if color is not available
InvalidParameterException if color is invalid or not supported
BridgeNotReachableException if bridge is not available
AuthenticationException if not authenticated
Definition at line 216 of file light.h.
TransitionTime_
Property<TransitionTime> hue4cpp::Light::TransitionTime_
Initial value:
{
            [this]() { return _transitionTime; },
            [this](TransitionTime& value) {
                SetPropertyValueAndNotify<&Light::TransitionTime_>(_transitionTime, value);
            }
        }
Get or set the transition time for light changes.
Returns
Transition time in milliseconds
Note
This property does not affect the current state but will be used for subsequent operations
Definition at line 117 of file light.h.
XYColor_
Property<XYColor> hue4cpp::Light::XYColor_
Initial value:
{
            [this]() {
                try {
                    return getColor();
                }
                catch (const HueException&) {
                    throw;
                }
            },
            [this](XYColor& value) {
                try {
                    NotifyPropertyChanging<&Light::XYColor_>();
                    setColor(value);
                }
                catch (const HueException&) {
                    throw;
                }
            }
        }
Get or set the color in XY color space.
Exceptions
ResourceNotFoundException if color is not available
InvalidParameterException if color is invalid or not supported
BridgeNotReachableException if bridge is not available
AuthenticationException if not authenticated
Definition at line 188 of file light.h.
The documentation for this class was generated from the following files:
include/hue4cpp/light.h
src/light.cpp