hue4cpp: hue4cpp::json_utils Namespace Reference
hue4cpp::json_utils Namespace Reference
Utility functions for JSON handling.
Functions
nlohmann::json parse (const std::string &json_str)
Parse a JSON string.
template<typename T >
std::optional< T > getValue (const nlohmann::json &json, const std::string &key)
Safely get a value from a JSON object.
template<typename T >
T getValueOr (const nlohmann::json &json, const std::string &key, const T &default_value)
Get a value from a JSON object with a default.
template<typename T >
T getRequiredValue (const nlohmann::json &json, const std::string &key)
Get a required value from a JSON object.
std::string toString (const nlohmann::json &json, int indent=-1)
Convert a JSON object to a formatted string.
bool hasRequiredKeys (const nlohmann::json &json, const std::vector< std::string > &required_keys)
Check if a JSON object has all required keys.
nlohmann::json createObject (const std::map< std::string, nlohmann::json > &pairs)
Create a JSON object from key-value pairs.
Detailed Description
Utility functions for JSON handling.
Function Documentation
createObject()
nlohmann::json hue4cpp::json_utils::createObject (const std::map< std::string, nlohmann::json > & pairs)
Create a JSON object from key-value pairs.
Parameters
pairs Map of key-value pairs
Returns
JSON object
Definition at line 39 of file json_utils.cpp.
References getValue().
getRequiredValue()
template<typename T > T hue4cpp::json_utils::getRequiredValue (const nlohmann::json & json, const std::string & key)
Get a required value from a JSON object.
Template Parameters
T The type to extract
Parameters
json The JSON object
key The key to look up
Returns
The value
Exceptions
JsonParseException if key doesn't exist or has wrong type
Definition at line 84 of file json_utils.h.
References getValue().
getValue()
template<typename T > std::optional< T > hue4cpp::json_utils::getValue (const nlohmann::json & json, const std::string & key)
Safely get a value from a JSON object.
Template Parameters
T The type to extract
Parameters
json The JSON object
key The key to look up
Returns
Optional value if key exists and has correct type
Definition at line 45 of file json_utils.h.
Referenced by hue4cpp::Bridge::authenticate(), createObject(), hue4cpp::createSensorFromJson(), hue4cpp::Bridge::discoverNUPnP(), hue4cpp::Bridge::getLights(), getRequiredValue(), getValueOr(), hasRequiredKeys(), hue4cpp::Light::initFromJson(), hue4cpp::Sensor::initFromJson(), parse(), toString(), and hue4cpp::Bridge::validateAuthentication().
getValueOr()
template<typename T > T hue4cpp::json_utils::getValueOr (const nlohmann::json & json, const std::string & key, const T & default_value)
Get a value from a JSON object with a default.
Template Parameters
T The type to extract
Parameters
json The JSON object
key The key to look up
default_value The default value if key doesn't exist
Returns
The value or default
Definition at line 70 of file json_utils.h.
References getValue().
hasRequiredKeys()
bool hue4cpp::json_utils::hasRequiredKeys (const nlohmann::json & json, const std::vector< std::string > & required_keys)
Check if a JSON object has all required keys.
Parameters
json The JSON object
required_keys List of required keys
Returns
true if all keys exist, false otherwise
Definition at line 24 of file json_utils.cpp.
References getValue().
parse()
nlohmann::json hue4cpp::json_utils::parse (const std::string & json_str)
Parse a JSON string.
Parameters
json_str The JSON string to parse
Returns
Parsed JSON object
Exceptions
JsonParseException if parsing fails
Definition at line 6 of file json_utils.cpp.
References getValue().
Referenced by hue4cpp::Bridge::authenticate(), hue4cpp::Bridge::discoverNUPnP(), hue4cpp::Bridge::getLight(), hue4cpp::Bridge::getLights(), hue4cpp::Bridge::getLightState(), hue4cpp::Bridge::getSensor(), hue4cpp::Bridge::getSensorState(), hue4cpp::Sensor::isEnabled(), and hue4cpp::Bridge::validateAuthentication().
toString()
std::string hue4cpp::json_utils::toString (const nlohmann::json & json, int indent = -1)
Convert a JSON object to a formatted string.
Parameters
json The JSON object
indent Number of spaces for indentation (-1 for compact)
Returns
Formatted JSON string
Definition at line 16 of file json_utils.cpp.
References getValue().
Referenced by hue4cpp::Bridge::authenticate().