hue4cpp: hue4cpp::Result< T > Struct Template Reference
hue4cpp::Result< T > Struct Template Reference
Result type for operations that can fail.
#include <types.h>
Public Member Functions
Result ()
Result (T val)
Result (ErrorCode err, const std::string &msg="")
bool isSuccess () const
bool hasValue () const
operator bool () const
Public Attributes
std::optional< T > value
ErrorCode error
std::string error_message
Detailed Description
template<typename T>
struct hue4cpp::Result< T >
Result type for operations that can fail.
Template Parameters
T The type of the result value
Definition at line 190 of file types.h.
Constructor & Destructor Documentation
Result() [1/3]
template<typename T > hue4cpp::Result< T >::Result () inline
Definition at line 195 of file types.h.
Result() [2/3]
template<typename T > hue4cpp::Result< T >::Result (T val) inline explicit
Definition at line 196 of file types.h.
Result() [3/3]
template<typename T > hue4cpp::Result< T >::Result (ErrorCode err, const std::string & msg = "") inline
Definition at line 197 of file types.h.
Member Function Documentation
hasValue()
template<typename T > bool hue4cpp::Result< T >::hasValue () const inline
Definition at line 202 of file types.h.
References hue4cpp::Result< T >::value.
isSuccess()
template<typename T > bool hue4cpp::Result< T >::isSuccess () const inline
Definition at line 201 of file types.h.
References hue4cpp::Result< T >::error, and hue4cpp::Success.
Referenced by hue4cpp::Result< T >::operator bool(), and hue4cpp::Result< void >::operator bool().
operator bool()
template<typename T > hue4cpp::Result< T >::operator bool () const inline
Definition at line 204 of file types.h.
References hue4cpp::Result< T >::isSuccess().
Member Data Documentation
error
template<typename T > ErrorCode hue4cpp::Result< T >::error
Definition at line 192 of file types.h.
Referenced by hue4cpp::Result< T >::isSuccess(), and hue4cpp::Result< void >::isSuccess().
error_message
template<typename T > std::string hue4cpp::Result< T >::error_message
Definition at line 193 of file types.h.
value
template<typename T > std::optional<T> hue4cpp::Result< T >::value
Definition at line 191 of file types.h.
Referenced by hue4cpp::Result< T >::hasValue().
The documentation for this struct was generated from the following file:
include/hue4cpp/types.h